name: betdofe_app_new
description: Aplicativo de apostas esportivas BET DO FÉ
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6  # Para armazenar apostas

  # Login social
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.12
  shimmer: ^3.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2  # Para gráficos de ganhos e perdas
  intl: ^0.20.2  # Para formatar datas
  table_calendar: ^3.2.0
  font_awesome_flutter: ^9.2.0  # Reduzido para compatibilidade com flutter_signin_button
  flutter_multi_formatter: ^2.13.7
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo.svg   
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png
    - assets/login_background.png
    - assets/onboarding/money.png
    - assets/onboarding/chart.png
    - assets/onboarding/target.png
    - assets/stadium_background.png