name: betdofe_app_new
description: Aplicativo de apostas esportivas BET DO FE
publish_to: 'none'
version: 1.0.0+1  # Adicionado

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  sign_in_with_apple: ^7.0.1
 
  # Login social
  google_sign_in: ^6.2.1

  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  table_calendar: ^3.2.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.0
  flutter_colorpicker: ^1.1.0
  dropdown_button2: ^2.3.9
  fluttertoast: ^8.2.2

  # Utilitários
  async: ^2.12.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_splash.png
    - assets/logo.svg
    - assets/google.png
    - assets/apple.png
    - assets/login_background.png
    - assets/onboarding/money.png
    - assets/onboarding/chart.png
    - assets/onboarding/target.png
    - assets/stadium_background.png
    - assets/images/whatsapp_icon.png
    - assets/splash_background.png
    - assets/images/wooden_clipboard.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter_native_splash:
  color: "#1B5E20"
  image: "assets/logo_splash.png"
  android: true
  ios: true
  fullscreen: true