// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj4sQ48E-WAPGHU4vyt9EO5kpABV6GHXM',
    appId: '1:1019981443447:android:9b920bcf5396374fb9b172',
    messagingSenderId: '1019981443447',
    projectId: 'betdofeapp',
    storageBucket: 'betdofeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7RrSFBDWhQt_nV3iA1dtP93lUrTXRkTs',
    appId: '1:1019981443447:ios:bb48e6a56e5c3672b9b172',
    messagingSenderId: '1019981443447',
    projectId: 'betdofeapp',
    storageBucket: 'betdofeapp.firebasestorage.app',
    androidClientId: '1019981443447-uce27hsc87lmntmdasa5aejsdpqgpjia.apps.googleusercontent.com',
    iosClientId: '1019981443447-v5qbl9rck157eov2oqmtpmd40qfhde87.apps.googleusercontent.com',
    iosBundleId: 'com.example.betdofeAppNew',
  );
}
